### ISSUE TITLE
403 errors by default

### ISSUE THREAD

**Issue by johnboiles** [dvargas92495/terraform-aws-static-site#12]
I uploaded all my static files from my Next.js app to the bucket created by this Terraform module like so:

```bash
aws s3 sync --delete out/ s3://www.example.com/
```

The relevant Terraform is

```terraform
module "selfiesizer_com" {
  source  = "dvargas92495/static-site/aws"
  version = "3.1.5"

  www_is_main = true

  cdn_settings = {
    default_ttl = 360
    max_ttl     = 86400
  }

  domain = "example.com"

  providers = {
    aws.us-east-1 = aws
  }
}
```

But then upon opening `www.example.com` I would get 403 forbidden errors. I could manually go into the S3 console and add public permissions to each object every time I uploaded something new, but that was tedious and not very Terraform-y. I think the error is with the generated bucket policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::www.example.com/*",
            "Condition": {
                "StringEquals": {
                    "aws:UserAgent": ""
                }
            }
        }
    ]
}
```

If I remove the `Condition` block it works as expected. *What's the purpose of this `Condition` block and is it supposed to be there?*

I was also able to work around this by overriding the bucket policy with my own policy.

```terraform
data "aws_s3_bucket" "main_bucket" {
  bucket = module.static_site_example_com.bucket-name
}

resource "aws_s3_bucket_policy" "public_bucket_policy" {
  bucket = data.aws_s3_bucket.main_bucket.id

  policy = jsonencode({
    Version = "2012-10-17"
    Id      = "PublicBucketPolicy"
    Statement = [
      {
        Sid       = "AddPerm"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource = [
          "${data.aws_s3_bucket.main_bucket.arn}/*",
        ]
      },
    ]
  })
}
```

**Comment by johnboiles** [comment]
Reading the code a bit I believe this is because `secret` defaults to `""` and that doesn't seem to work. I think we should either make `secret` a non-empty string OR make it non-optional.

**Comment by dvargasfuertes** [comment]
We should make it non-optional, that's a great callout. this is to ensure that only the CloudFront distribution can access the files from S3

**Comment by dvargasfuertes** [comment]
closed by https://github.com/dvargas92495/terraform-aws-static-site/commit/478a3578d461651d456564d69db0cd954ac7bd59

**Comment by johnboiles** [comment]
Thanks for the quick fix!
